//used to test the routes, install rest client in visual studio code
//getting all menu items
GET http://localhost:3000/menu

###
//getting a single menu item by id
GET http://localhost:3000/menu/66039d95513343748492c8ae
###
//creating a menu item
POST http://localhost:3000/menu
Content-Type: application/json

{
    "name": "Glazed Donut",
    "price": 4.99,
    "image": "donut.jpg",
    "description": "Warm fresh donut covered with homemade glaze",
    "macronutrients":{
        "calories": 450,
        "fats": 30,
        "carbs": 45,
        "protein": 8
    },
    "allergens": "none",
    "rewardsPointsCOST": 200,
    "rewardsPointsADD": 100


}

###
//deleting a menu item
DELETE http://localhost:3000/menu/66039d95513343748492c8ae

###
//getting all users
GET http://localhost:3000/user

###
//creating a user
POST http://localhost:3000/user
Content-Type: application/json

{
    "username": "dragon",
    "password": "bananaman",
    "rewardPoints": 0


}

###
// Signup (account creation) Request

POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "username": "matthewh",
    "password": "hughes",
    "rewardPoints": 0

}

###
// Login Request

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "batmans",
    "password": "bananaman",
    "rewardPoints": 0

}

###
// Auth request 
GET  http://localhost:3000/auth HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhdG1hbnMiLCJpYXQiOjE3MTMzMTk3MTcsImV4cCI6MTcxMzY3OTcxN30.xqf2Vo_qm5JZCR15zhepVF00jOH-z8wYZlKpdBNc1hY

###

POST http://localhost:3000/user
Content-Type: application/json

{
    "username": "functionality",
    "password": "working",
    "rewardPoints": 0
}

###

POST http://localhost:3000/user
Content-Type: application/json

{
    "username": "gigachad",
    "password": "cat",
    "rewardPoints": 0
}

###
GET http://localhost:3000/user/661d8f23d133d4fd4a5d5824


###
//updating a user **important
PATCH http://localhost:3000/user/661d8f23d133d4fd4a5d5824
Content-Type: application/json

{
    "rewardPoints": 2000
}

###
//deleting a user
DELETE http://localhost:3000/user/66039fed537254b107ee1261

###
//getting all toppings
GET http://localhost:3000/topping

###
//creating a topping
POST http://localhost:3000/topping
Content-Type: application/json

{
    "name": "chocolate syrup",
    "price": 1.99,
    "rewardPointsCOST": 0,
    "rewardPointsADD": 0

}

###
//deleting a topping
DELETE http://localhost:3000/topping/661a8487f5caf23ec7f8ed59

